import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import Sidebar from "@/layout/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { checkAuthClient } from "@/app/api/auth/checkAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }) {
  const authResult = await checkAuthClient();
  return (
    <html lang="en">
      <body className={inter.className}>
      <Sidebar authenticated={authResult.authenticated} />

        {children}
        <Toaster />
        </body>
    </html>
  );
}