import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import Sidebar from "@/layout/sidebar";
import { Toaster } from "@/components/ui/toaster";
import { requireStaffAccount } from "@/lib/serverAuth";
import AdminSessionProvider from "@/components/admin/AdminSessionProvider";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }) {
  const session = await requireStaffAccount();
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader showSpinner={false} />
      <AdminSessionProvider sessionToken={session.user.sessionToken}>
      <Sidebar authenticated={true} />

        {children}
        <Toaster />
        </AdminSessionProvider>
        </body>
    </html>
  );
}
