import "@/app/styles/globals.css";

export const metadata = {
  title: 'Form Share Undangan - SewaUndangan',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
